### ISSUE TITLE
Support methods of Movies

### ISSUE THREAD

**Issue by adborbas** [adborbas/TMDbKit#31]
Support the following methods of Movies:
 - [x] Get Details PR:
 - [x] Get Alternative Titles PR:
 - [x] Get Credits PR:
 - [x] Get Images PR:
 - [x] Get Release Dates PR: #48 
 - [x] Get Recommendations PR: #50 
 - [x] Get Lists PR: #51 
 - [x] Get Now Playing PR: #42 
 - [x] Get Popular PR: #51
 - [x] Get Top Rated PR: #51
 - [x] Get Upcoming PR: #51
